apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: nas-demo
spec:
  subresources:
    status: {}
  components:
    - componentName: ecs-vpc
      instanceName: vpc
      traits:
        - name: DeletionPolicy
          properties:
            policy: "Retain"
    - componentName: ecs-vswitch
      instanceName: vswitch
      parameterValues:
        - name: VpcId
          from:
            component: vpc
            fieldPath: ".status.VpcId"
      traits:
        - name: DeletionPolicy
          properties:
            policy: "Delete"
    - componentName: nas-access-group
      instanceName: nasAccessGroup
      traits:
        - name: DeletionPolicy
          properties:
            policy: "Delete"
    - componentName: nas-file-system
      instanceName: nasFileSystem
      traits:
        - name: DeletionPolicy
          properties:
            policy: "Delete"
    - componentName: nas-mount-target
      instanceName: nasMountTarget
      parameterValues:
        - name: AccessGroupName
          from:
            component: nasAccessGroup
            fieldPath: ".status.AccessGroupName"
        - name: FileSystemId
          from:
            component: nasFileSystem
            fieldPath: ".status.FileSystemId"
        - name: VpcId
          from:
            component: vpc
            fieldPath: ".status.VpcId"
        - name: VSwitchId
          from:
            component: vswitch
            fieldPath: ".status.VSwitchId"
      traits:
        - name: DeletionPolicy
          properties:
            policy: "Delete"

#  scopes:
#    - name: resource-identity
#      type: oam.alibaba.dev/v1.ResourceIdentity
#      properties:
#        appName: {fromWhichApp}
#        aliyunAccountUid: {userWhoCreatedResources}
#        regionId: {regionWhereCreateResources}