apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: actiontrail-traillogging
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ACTIONTRAIL_TrailLogging
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Name",
        "Enable"
      ],
      "properties": {
        "Enable": {
          "type": "boolean",
          "description": "Whether to enable the trail logging."
        },
        "Name": {
          "type": "string",
          "description": "The name of the trail to be enabled."
        }
      }
    }
