apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: apigateway-group
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ApiGateway_Group
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "GroupName"
      ],
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of the Group, less than 180 characters."
        },
        "GroupName": {
          "type": "string",
          "description": "The name of the Group.Need [4, 50] Chinese\\English\\Number characters or \"_\",and should start with Chinese/English character."
        }
      }
    }
