apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: bss-waitorder
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: BSS_WaitOrder
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "OrderIds"
      ],
      "properties": {
        "CancelOnDelete": {
          "type": "boolean",
          "description": "Cancel order where delete the resource. Ignore the paid order. Default true",
          "default": true
        },
        "OrderIds": {
          "type": "array",
          "description": "A list of order ids.",
          "items": {},
          "minItems": 1
        },
        "WaitForOrderProduced": {
          "type": "boolean",
          "description": "Wait util all orders related ROS resources are produced. \nSupport ALIYUN::ECS::PrepayInstance, ALIYUN::RDS::PrepayDBInstance, ALIYUN::SLB::LoadBalancer, ALIYUN::VPC::EIP, ALIYUN::VPC::VpnGateway.",
          "default": false
        }
      }
    }
