apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: cas-certificate
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: CAS_Certificate
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Cert",
        "Name",
        "Key"
      ],
      "properties": {
        "Cert": {
          "type": "string",
          "description": "Specify the content of the certificate. To use the PEM encoding format."
        },
        "Key": {
          "type": "string",
          "description": "Specify the certificate private key content. To use the PEM encoding format."
        },
        "Lang": {
          "type": "string",
          "description": "Specifies the language type for requesting and receiving messages."
        },
        "Name": {
          "type": "string",
          "description": "Custom certificate name. The certificate name under a user cannot be duplicated."
        },
        "SourceIp": {
          "type": "string",
          "description": "Specifies the source IP address of the request."
        }
      }
    }
