apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: cdn-domainconfig
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: CDN_DomainConfig
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Functions",
        "DomainNames"
      ],
      "properties": {
        "DomainNames": {
          "type": "string",
          "description": "Your accelerated domain name, separated by commas in English."
        },
        "Functions": {
          "type": "string",
          "description": "function list, please refer to the CDN documentation for details."
        }
      }
    }
