apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: cen-ceninstance
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: CEN_CenInstance
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "Description": {
          "type": "string",
          "description": "The description of the instance.\nThe name can be 2-256 characters in length. It can start with an uppercase letter, lowercase letter, or Chinese character. It can contain numbers, underscores (_), and hyphens (-), but cannot start with http:// or https://."
        },
        "Name": {
          "type": "string",
          "description": "The name of the instance.\nThe name can be 2-128 characters in length. It can start with an uppercase letter, lowercase letter, or Chinese character. It can contain numbers, underscores (_), and hyphens (-), but cannot start with http:// or https://."
        }
      }
    }
