apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: drds-drdsinstance
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: DRDS_DrdsInstance
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Description",
        "Type",
        "Quantity",
        "InstanceSeries",
        "Specification",
        "ZoneId",
        "PayType"
      ],
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of the DRDS instance, 2-128 characters"
        },
        "Duration": {
          "type": "integer",
          "description": "The number of cycles ordered. When PricingCycle=year, the value is 1-3; when PricingCycle=month, the value is 1-9. The parameter takes effect when the payment type is drdsPre.",
          "minimum": 1,
          "maximum": 9
        },
        "InstanceSeries": {
          "type": "string",
          "description": "drds.sn1.4c8g Starter Edition; drds.sn1.8c16g Standard Edition; drds.sn1.16c32g Business Edition; drds.sn1.32c64g Ultimate Edition",
          "Enum": [
            "drds.sn1.4c8g",
            "drds.sn1.8c16g",
            "drds.sn1.16c32g",
            "drds.sn1.32c64g"
          ]
        },
        "IsAutoRenew": {
          "type": "boolean",
          "description": "Whether to renew the fee automatically, if it is purchased on a monthly basis, it will automatically renew for one month, and if it is purchased on an annual basis, it will automatically renew for one year. The parameter takes effect when the payment type is drdsPre."
        },
        "PayType": {
          "type": "string",
          "description": "For the type of payment, see \"Payment Type Parameter Table\"",
          "Enum": [
            "drdsPost",
            "drdsPre"
          ]
        },
        "PricingCycle": {
          "type": "string",
          "description": "The unit of the order period, year: year, month: month. The parameter takes effect when the payment type is drdsPre.",
          "Enum": [
            "year",
            "month"
          ]
        },
        "Quantity": {
          "type": "integer",
          "description": "Purchase quantity",
          "minimum": 1
        },
        "Specification": {
          "type": "string",
          "description": "The example specification, for example, drds.sn1.4c8g.8C16G, consists of the DRDS instance series (drds.sn1.4c8g) plus a specific example specification (8C16G). For the DRDS instance specification value range, see: Distributed Relational Database Service Specifications and Pricing"
        },
        "Type": {
          "type": "string",
          "description": "Instance type, instance type 0 - shared instance 1 - exclusive instance, in addition, this parameter can also pass PRIVATE and PUBLIC to represent exclusive instance and shared instance respectively",
          "Enum": [
            "0",
            "1",
            "PRIVATE",
            "PUBLIC"
          ]
        },
        "VpcId": {
          "type": "string",
          "description": "Virtual private network ID, must be specified when creating a DRDS for VPC network type"
        },
        "VswitchId": {
          "type": "string",
          "description": "Virtual switch ID, must be specified when creating a DRDS for VPC network type"
        },
        "ZoneId": {
          "type": "string",
          "description": "Availability zone, an available zone belongs to a certain zone, such as Hangzhou Availability Zone A (cn-hangzhou-a) belongs to the region Hangzhou (cn-hangzhou)"
        }
      }
    }
