apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-joinsecuritygroup
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_JoinSecurityGroup
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "SecurityGroupId"
      ],
      "properties": {
        "InstanceId": {
          "type": "string",
          "description": "Instance Id to the join the security group."
        },
        "InstanceIdList": {
          "type": "array",
          "description": "The comma delimited instance id list.If the property \"InstanceId\" is setting, this property will be ignored.",
          "items": {}
        },
        "NetworkInterfaceList": {
          "type": "array",
          "description": "Network interface list.",
          "items": {}
        },
        "SecurityGroupId": {
          "type": "string",
          "description": "Security group id to join."
        }
      }
    }
