apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-diskattachment
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_DiskAttachment
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "InstanceId",
        "DiskId"
      ],
      "properties": {
        "DeleteWithInstance": {
          "type": "boolean",
          "description": "If property is true, the disk will be deleted while instance is deleted, if property is false, the disk will be retain after instance is deleted."
        },
        "Device": {
          "type": "string",
          "description": "The device where the volume is exposed on the instance. could be /dev/xvd[b-z]. If not specification, will use default value."
        },
        "DiskId": {
          "type": "string",
          "description": "The disk id to attached."
        },
        "InstanceId": {
          "type": "string",
          "description": "The instanceId to attach the disk."
        }
      }
    }
