apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-sshkeypair
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_SSHKeyPair
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "KeyPairName"
      ],
      "properties": {
        "KeyPairName": {
          "type": "string",
          "description": "SSH key pair name. It must be unique. [2, 128] characters. All character sets are supported. Do not start with a special character, digit, http://, or https://. It can contain digits, \".\", \"_\", or \"-\"."
        },
        "PublicKeyBody": {
          "type": "string",
          "description": "SSH Public key. If PublicKeyBody is specified, existed public key body will be imported instead of creating new SSH key pair."
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        }
      }
    }
