apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-natgateway
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_NatGateway
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "VSwitchId",
        "VpcId"
      ],
      "properties": {
        "BandwidthPackage": {
          "type": "array",
          "description": "Create bandwidth package for NAt gateway. Max support 4 bandwidth packages.",
          "items": {
            "type": "object",
            "properties": {
              "Bandwidth": {
                "type": "integer",
                "description": "Bandwidth, [5-5000]M for PayByBandwidth, [5-50]M for PayByTraffic.",
                "default": 5,
                "minimum": 5,
                "maximum": 5000
              },
              "InternetChargeType": {
                "type": "string",
                "description": "Nat Gateway internet access charge type.Support 'PayByBandwidth' and 'PayByTraffic' only. Default is PayByTraffic",
                "default": "PayByTraffic",
                "Enum": [
                  "PayByBandwidth",
                  "PayByTraffic"
                ]
              },
              "IpCount": {
                "type": "integer",
                "description": "Total internet IPs of this Bandwidth package, [1-5]",
                "minimum": 1,
                "maximum": 5
              },
              "ZoneId": {
                "type": "string",
                "description": "The availability zone where the bandwidth package will be created."
              }
            }
          }
        },
        "DeletionForce": {
          "type": "boolean",
          "description": "Whether force delete the relative snat and dnat entries in the net gateway and unbind eips. Default value is false.",
          "default": false
        },
        "DeletionProtection": {
          "type": "boolean",
          "description": "Whether to enable deletion protection.\nDefault to False.",
          "default": false
        },
        "Description": {
          "type": "string",
          "description": "Description of the NAT gateway, [2, 256] characters. Do not fill or empty, the default is empty."
        },
        "NatGatewayName": {
          "type": "string",
          "description": "Display name of the NAT gateway, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "Spec": {
          "type": "string",
          "description": "NAT gateway specification. Now support 'Small|Middle|Large'",
          "Enum": [
            "Small",
            "Middle",
            "Large"
          ]
        },
        "VSwitchId": {
          "type": "string",
          "description": "The VSwitch id to create NAT gateway."
        },
        "VpcId": {
          "type": "string",
          "description": "The VPC id to create NAT gateway."
        }
      }
    }
