apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-networkinterface
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_NetworkInterface
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "SecurityGroupId",
        "VSwitchId"
      ],
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of your ENI. It is a string of [2, 256] English or Chinese characters."
        },
        "NetworkInterfaceName": {
          "type": "string",
          "description": "Name of your ENI. It is a string of [2, 128]  Chinese or English characters. It must begin with a letter and can contain numbers, underscores (_), colons (:), or hyphens (-)."
        },
        "PrimaryIpAddress": {
          "type": "string",
          "description": "The primary private IP address of the ENI.  The specified IP address must have the same Host ID as the VSwitch. If no IP addresses are specified, a random network ID is assigned for the ENI."
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        },
        "SecurityGroupId": {
          "type": "string",
          "description": "The ID of the security group that the ENI joins. The security group and the ENI must be in a same VPC."
        },
        "VSwitchId": {
          "type": "string",
          "description": "VSwitch ID of the specified VPC. Specifies the switch ID for the VPC."
        }
      }
    }
