apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-instanceclone
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_InstanceClone
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "SourceInstanceId"
      ],
      "properties": {
        "BackendServerWeight": {
          "type": "integer",
          "description": "The weight of backend server of load balancer. From 0 to 100, 0 means offline. Default is 100.",
          "default": 100,
          "maximum": 100
        },
        "DeletionProtection": {
          "type": "boolean",
          "description": "Whether an instance can be released manually through the console or API, deletion protection only support postPaid instance ",
          "Enum": [
            true,
            false
          ]
        },
        "Description": {
          "type": "string",
          "description": "Description of the instance, [2, 256] characters. Do not fill or empty, the default is empty."
        },
        "DiskMappings": {
          "type": "array",
          "description": "Disk mappings to attach to instance. Max support 16 disks.\nIf the image contains a data disk, you can specify other parameters of the data disk via the same value of parameter \"Device\". If parameter \"Category\" is not specified, it will be cloud_efficiency instead of \"Category\" of data disk in the image.",
          "items": {
            "type": "object",
            "required": [
              "Size"
            ],
            "properties": {
              "Category": {
                "type": "string",
                "description": "The volume type.Now support: cloud|cloud_efficiency|cloud_ssd|cloud_essd|ephemeral_ssd. Default is cloud_efficiency.",
                "default": "cloud_efficiency",
                "Enum": [
                  "cloud",
                  "cloud_efficiency",
                  "cloud_ssd",
                  "cloud_essd",
                  "ephemeral_ssd"
                ]
              },
              "Description": {
                "type": "string",
                "description": "Description of the disk, [2, 256] characters. Do not fill or empty, the default is empty."
              },
              "Device": {
                "type": "string",
                "description": "The device where the volume is exposed on the instance. could be /dev/xvd[a-z]. If not specification, will use default value."
              },
              "DiskName": {
                "type": "string",
                "description": "Display name of the disk, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'."
              },
              "PerformanceLevel": {
                "type": "string",
                "description": "The performance level of the enhanced SSD used as the Nth data disk.Default value: PL1. Valid values:PL1: A single enhanced SSD delivers up to 50,000 random read/write IOPS.PL2: A single enhanced SSD delivers up to 100,000 random read/write IOPS.PL3: A single enhanced SSD delivers up to 1,000,000 random read/write IOPS."
              },
              "Size": {
                "type": "string",
                "description": "The size of the volume, unit in GB.Value range: cloud: [5,2000], cloud_efficiency: [20,32768], cloud_ssd: [20,32768], cloud_essd: [20,32768], ephemeral_ssd: [5,800].The value should be equal to or greater than the specific snapshot."
              },
              "SnapshotId": {
                "type": "string",
                "description": "ID of the snapshot to create the volume."
              }
            }
          },
          "maxItems": 16
        },
        "ImageId": {
          "type": "string",
          "description": "Image ID to create ecs instance."
        },
        "InstanceChargeType": {
          "type": "string",
          "description": "Instance Charge type, allowed value: Prepaid and Postpaid. If specified Prepaid, please ensure you have sufficient balance in your account. Or instance creation will be failure. Default value is Postpaid.",
          "default": "PostPaid",
          "Enum": [
            "PrePaid",
            "PostPaid"
          ]
        },
        "InstanceName": {
          "type": "string",
          "description": "Display name of the instance, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "InternetMaxBandwidthIn": {
          "type": "integer",
          "description": "Max internet out band width setting, unit in Mbps(Mega bit per second). The range is [1,200], default is 200 Mbps.",
          "default": 200,
          "minimum": 1,
          "maximum": 200
        },
        "KeyPairName": {
          "type": "string",
          "description": "SSH key pair name."
        },
        "LoadBalancerIdToAttach": {
          "type": "string",
          "description": "After the instance is created. Automatic attach it to the load balancer."
        },
        "Password": {
          "type": "string",
          "description": "Password of created ecs instance. Must contain at least 3 types of special character, lower character, upper character, number."
        },
        "Period": {
          "type": "number",
          "description": "Prepaid time period. Unit is month, it could be from 1 to 9 or 12, 24, 36, 48, 60. Default value is 1.",
          "default": 1,
          "Enum": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            12,
            24,
            36,
            48,
            60
          ]
        },
        "RamRoleName": {
          "type": "string",
          "description": "Instance RAM role name. The name is provided and maintained by Resource Access Management (RAM) and can be queried using ListRoles. For more information, see RAM API CreateRole and ListRoles."
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        },
        "SecurityGroupId": {
          "type": "string",
          "description": "Security group to create ecs instance. For classic instance need the security group not belong to VPC, for VPC instance, please make sure the security group belong to specified VPC."
        },
        "SourceInstanceId": {
          "type": "string",
          "description": "Source ecs instance used to copy properties to clone new ecs instance. It will copy the InstanceType, ImageId, InternetChargeType, InternetMaxBandwidthIn, InternetMaxBandwidthOut and the system disk and data disk configurations. If the instance network is VPC, it will also clone the relative properties. If specified instance with more than one security group, it will use the first security group to create instance. you can also specify the SecurityGroupId to override it."
        },
        "SpotPriceLimit": {
          "type": "string",
          "description": "The hourly price threshold of a instance, and it takes effect only when parameter InstanceChargeType is PostPaid. Three decimals is allowed at most. "
        },
        "SpotStrategy": {
          "type": "string",
          "description": "The spot strategy of a Pay-As-You-Go instance, and it takes effect only when parameter InstanceChargeType is PostPaid. Value range: \"NoSpot: A regular Pay-As-You-Go instance\", \"SpotWithPriceLimit: A price threshold for a spot instance, \"\"SpotAsPriceGo: A price that is based on the highest Pay-As-You-Go instance. \"Default value: NoSpot.",
          "Enum": [
            "NoSpot",
            "SpotWithPriceLimit",
            "SpotAsPriceGo"
          ]
        },
        "Tags": {
          "type": "array",
          "description": "Tags to attach to instance. Max support 20 tags to add during create instance. Each tag with two properties Key and Value, and Key is required.",
          "items": {
            "type": "object",
            "required": [
              "Key"
            ],
            "properties": {
              "Key": {
                "type": "string"
              },
              "Value": {
                "type": "string"
              }
            }
          },
          "maxItems": 20
        },
        "ZoneId": {
          "type": "string",
          "description": "current zone to create the instance."
        }
      }
    }
