apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-vpc
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_VPC
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "CidrBlock": {
          "type": "string",
          "description": "The IP address range of the VPC in the CIDR block form. You can use the following IP address ranges and their subnets:\n10.0.0.0/8\n172.16.0.0/12 (Default)\n192.168.0.0/16"
        },
        "Description": {
          "type": "string",
          "description": "Description of the vpc, [2, 256] characters. Do not fill or empty, the default is empty."
        },
        "EnableIpv6": {
          "type": "boolean",
          "description": "Whether to enable an IPv6 network cidr, the value is:False (default): not turned on.True: On.",
          "default": false
        },
        "Ipv6CidrBlock": {
          "type": "string",
          "description": "IPv6 network cidr of the VPC.",
          "minLength": 1
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        },
        "VpcName": {
          "type": "string",
          "description": "Display name of the vpc instance, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        }
      }
    }
