apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-securitygroupclone
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_SecurityGroupClone
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "SourceSecurityGroupId"
      ],
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of the security group, [2, 256] characters. Do not fill or empty, the default is empty."
        },
        "DestinationRegionId": {
          "type": "string",
          "description": "Clone security group to the specified region. Default to current region.",
          "default": "CURRENT"
        },
        "NetworkType": {
          "type": "string",
          "description": "Clone new security group as classic network type. If the VpcId is specified, the value will be ignored.",
          "Enum": [
            "Classic"
          ]
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        },
        "SecurityGroupName": {
          "type": "string",
          "description": "Display name of the security group, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "SecurityGroupType": {
          "type": "string",
          "description": "The type of the security group. Valid values:\nnormal: basic security group\nenterprise: advanced security group",
          "Enum": [
            "normal",
            "enterprise"
          ]
        },
        "SourceSecurityGroupId": {
          "type": "string",
          "description": "Source security group ID is used to copy properties to clone new security group. If the NetworkType and VpcId is not specified, the same security group will be cloned. If NetworkType or VpcId is specified, only proper security group rules will be cloned."
        },
        "VpcId": {
          "type": "string",
          "description": "Physical ID of the VPC."
        }
      }
    }
