apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-securitygroup
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_SecurityGroup
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of the security group, [2, 256] characters. Do not fill or empty, the default is empty."
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "Resource group id."
        },
        "SecurityGroupEgress": {
          "type": "array",
          "description": "egress rules for the security group.",
          "items": {
            "type": "object",
            "required": [
              "PortRange",
              "IpProtocol"
            ],
            "properties": {
              "Description": {
                "type": "string",
                "description": "Description of the security group rule, [1, 512] characters. The default is empty.",
                "minLength": 1,
                "maxLength": 512
              },
              "DestCidrIp": {
                "type": "string",
                "description": "Dest CIDR Ip Address range. Only IPV4 supported."
              },
              "DestGroupId": {
                "type": "string",
                "description": "Dest Group Id"
              },
              "DestGroupOwnerAccount": {
                "type": "string",
                "description": "Dest Group Owner Account"
              },
              "DestGroupOwnerId": {
                "type": "string",
                "description": "Dest Group Owner Account ID"
              },
              "IpProtocol": {
                "type": "string",
                "description": "Ip protocol for in rule.",
                "Enum": [
                  "tcp",
                  "udp",
                  "icmp",
                  "gre",
                  "all"
                ]
              },
              "Ipv6DestCidrIp": {
                "type": "string",
                "description": "Destination IPv6 CIDR address segment. Supports IP address ranges in CIDR format and IPv6 format.\nNote Only VPC type IP addresses are supported."
              },
              "NicType": {
                "type": "string",
                "description": "Network type, could be 'internet' or 'intranet'. Default value is internet.",
                "Enum": [
                  "internet",
                  "intranet"
                ]
              },
              "Policy": {
                "type": "string",
                "description": "Authorization policies, parameter values can be: accept (accepted access), drop (denied access). Default value is accept.",
                "Enum": [
                  "accept",
                  "drop"
                ]
              },
              "PortRange": {
                "type": "string",
                "description": "Ip protocol relative port range. For tcp and udp, the port rang is [1,65535], using format '1/200'For icmp|gre|all protocel, the port range should be '-1/-1'"
              },
              "Priority": {
                "type": "integer",
                "description": "Authorization policies priority range[1, 100]",
                "default": 1,
                "minimum": 1,
                "maximum": 100
              },
              "SecurityGroupId": {
                "type": "string",
                "description": "Id of the security group."
              }
            }
          }
        },
        "SecurityGroupIngress": {
          "type": "array",
          "description": "Ingress rules for the security group.",
          "items": {
            "type": "object",
            "required": [
              "PortRange",
              "IpProtocol"
            ],
            "properties": {
              "Description": {
                "type": "string",
                "description": "Description of the security group rule, [1, 512] characters. The default is empty.",
                "minLength": 1,
                "maxLength": 512
              },
              "IpProtocol": {
                "type": "string",
                "description": "Ip protocol for in rule.",
                "Enum": [
                  "tcp",
                  "udp",
                  "icmp",
                  "gre",
                  "all"
                ]
              },
              "Ipv6SourceCidrIp": {
                "type": "string",
                "description": "Source IPv6 CIDR address segment. Supports IP address ranges in CIDR format and IPv6 format.\nNote Only VPC type IP addresses are supported."
              },
              "NicType": {
                "type": "string",
                "description": "Network type, could be 'internet' or 'intranet'. Default value is internet.",
                "Enum": [
                  "internet",
                  "intranet"
                ]
              },
              "Policy": {
                "type": "string",
                "description": "Authorization policies, parameter values can be: accept (accepted access), drop (denied access). Default value is accept.",
                "Enum": [
                  "accept",
                  "drop"
                ]
              },
              "PortRange": {
                "type": "string",
                "description": "Ip protocol relative port range. For tcp and udp, the port rang is [1,65535], using format '1/200'For icmp|gre|all protocel, the port range should be '-1/-1'"
              },
              "Priority": {
                "type": "integer",
                "description": "Authorization policies priority range[1, 100]",
                "default": 1,
                "minimum": 1,
                "maximum": 100
              },
              "SecurityGroupId": {
                "type": "string",
                "description": "Id of the security group."
              },
              "SourceCidrIp": {
                "type": "string",
                "description": "Source CIDR Ip Address range. Only IPV4 supported."
              },
              "SourceGroupId": {
                "type": "string",
                "description": "Source Group Id"
              },
              "SourceGroupOwnerAccount": {
                "type": "string",
                "description": "Source Group Owner Account"
              },
              "SourceGroupOwnerId": {
                "type": "string",
                "description": "Source Group Owner Account ID"
              },
              "SourcePortRange": {
                "type": "string",
                "description": "The range of the ports enabled by the source security group for the transport layer protocol. Valid values: TCP/UDP: Value range: 1 to 65535. The start port and the end port are separated by a slash (/). Correct example: 1/200. Incorrect example: 200/1.ICMP: -1/-1.GRE: -1/-1.ALL: -1/-1."
              }
            }
          }
        },
        "SecurityGroupName": {
          "type": "string",
          "description": "Display name of the security group, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "SecurityGroupType": {
          "type": "string",
          "description": "The type of the security group. Valid values:\nnormal: basic security group\nenterprise: advanced security group",
          "Enum": [
            "normal",
            "enterprise"
          ]
        },
        "Tags": {
          "type": "array",
          "description": "Tags to attach to instance. Max support 20 tags to add during create instance. Each tag with two properties Key and Value, and Key is required.",
          "items": {
            "type": "object",
            "required": [
              "Key"
            ],
            "properties": {
              "Key": {
                "type": "string"
              },
              "Value": {
                "type": "string"
              }
            }
          },
          "maxItems": 20
        },
        "VpcId": {
          "type": "string",
          "description": "Physical ID of the VPC."
        }
      }
    }
