apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-securitygroupegress
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_SecurityGroupEgress
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "PortRange",
        "IpProtocol"
      ],
      "properties": {
        "Description": {
          "type": "string",
          "description": "Description of the security group rule, [1, 512] characters. The default is empty.",
          "minLength": 1,
          "maxLength": 512
        },
        "DestCidrIp": {
          "type": "string",
          "description": "Dest CIDR Ip Address range. Only IPV4 supported."
        },
        "DestGroupId": {
          "type": "string",
          "description": "Dest Group Id"
        },
        "DestGroupOwnerId": {
          "type": "string",
          "description": "Dest Group Owner Account ID"
        },
        "IpProtocol": {
          "type": "string",
          "description": "Ip protocol for in rule.",
          "Enum": [
            "tcp",
            "udp",
            "icmp",
            "gre",
            "all"
          ]
        },
        "Ipv6DestCidrIp": {
          "type": "string",
          "description": "Destination IPv6 CIDR address segment. Supports IP address ranges in CIDR format and IPv6 format.\nNote Only VPC type IP addresses are supported."
        },
        "NicType": {
          "type": "string",
          "description": "Network type, could be 'internet' or 'intranet'. Default value is internet.",
          "Enum": [
            "internet",
            "intranet"
          ]
        },
        "Policy": {
          "type": "string",
          "description": "Authorization policies, parameter values can be: accept (accepted access), drop (denied access). Default value is accept.",
          "Enum": [
            "accept",
            "drop"
          ]
        },
        "PortRange": {
          "type": "string",
          "description": "Ip protocol relative port range. For tcp and udp, the port rang is [1,65535], using format '1/200'For icmp|gre|all protocel, the port range should be '-1/-1'"
        },
        "Priority": {
          "type": "integer",
          "description": "Authorization policies priority range[1, 100]",
          "default": 1,
          "minimum": 1,
          "maximum": 100
        },
        "SecurityGroupId": {
          "type": "string",
          "description": "Id of the security group."
        }
      }
    }
