apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-launchtemplate
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_LaunchTemplate
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "LaunchTemplateName"
      ],
      "properties": {
        "AutoReleaseTime": {
          "type": "string",
          "description": "Auto release time for created instance, Follow ISO8601 standard using UTC time. format is 'yyyy-MM-ddTHH:mm:ssZ'. Not bigger than 3 years from this day onwards"
        },
        "Description": {
          "type": "string",
          "description": "Description of the instance, [2, 256] characters."
        },
        "DiskMappings": {
          "type": "array",
          "description": "Disk mappings to attach to instance. Max support 16 disks.",
          "items": {
            "type": "object",
            "properties": {
              "Category": {
                "type": "string",
                "description": "The volume type.Now support: cloud|cloud_efficiency|cloud_ssd|cloud_essd|ephemeral_ssd. ",
                "Enum": [
                  "cloud",
                  "cloud_efficiency",
                  "cloud_ssd",
                  "cloud_essd",
                  "ephemeral_ssd"
                ]
              },
              "DeleteWithInstance": {
                "type": "boolean",
                "description": "Whether data disk should be released with instance."
              },
              "Description": {
                "type": "string",
                "description": "Description of the disk, [2, 256] characters."
              },
              "DiskName": {
                "type": "string",
                "description": "Display name of the disk, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'."
              },
              "Encrypted": {
                "type": "boolean",
                "description": "Whether data disk is encrypted."
              },
              "Size": {
                "type": "string",
                "description": "The size of the volume, unit in GB.Value range: cloud: [5,2000], cloud_efficiency: [20,32768], cloud_ssd: [20,32768], cloud_essd: [20,32768] ephemeral_ssd: [5,800].The value should be equal to or greater than the specific snapshot."
              },
              "SnapshotId": {
                "type": "string",
                "description": "ID of the snapshot to create the volume."
              }
            }
          },
          "maxItems": 16
        },
        "HostName": {
          "type": "string",
          "description": "Host name of created ecs instance. at least 2 characters, and '.' '-' Is not the first and last characters as hostname, not continuous use. Windows platform can be up to 15 characters, allowing letters (without limiting case), numbers and '-', and does not support the number of points, not all is digital ('.').Other (Linux, etc.) platform up to 30 characters, allowing support number multiple points for the period between the points, each permit letters (without limiting case), numbers and '-' components."
        },
        "ImageId": {
          "type": "string",
          "description": "Image ID to create ecs instance."
        },
        "InstanceName": {
          "type": "string",
          "description": "Display name of the instance, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "InstanceType": {
          "type": "string",
          "description": "Ecs instance supported instance type, make sure it should be correct."
        },
        "InternetChargeType": {
          "type": "string",
          "description": "Instance internet access charge type.Support 'PayByBandwidth' and 'PayByTraffic' only.",
          "Enum": [
            "PayByBandwidth",
            "PayByTraffic"
          ]
        },
        "InternetMaxBandwidthIn": {
          "type": "integer",
          "description": "Max internet in bandwidth in Mbps(Mega bit per second). The range is [1,200].",
          "minimum": 1,
          "maximum": 200
        },
        "InternetMaxBandwidthOut": {
          "type": "integer",
          "description": "Max internet out bandwidth in Mbps(Mega bit per second). Range is [0,200].While the property is not 0, public ip will be assigned for instance.",
          "maximum": 200
        },
        "IoOptimized": {
          "type": "string",
          "description": "The 'optimized' instance can provide better IO performance. Support 'none' and 'optimized' only.",
          "Enum": [
            "none",
            "optimized"
          ]
        },
        "KeyPairName": {
          "type": "string",
          "description": "SSH key pair name."
        },
        "LaunchTemplateName": {
          "type": "string",
          "description": "The name of launch template."
        },
        "NetworkInterfaces": {
          "type": "array",
          "description": "Elastic network interfaces to be attached to instance.",
          "items": {
            "type": "object",
            "properties": {
              "Description": {
                "type": "string",
                "description": "Description of your ENI. It is a string of [2, 256] English or Chinese characters."
              },
              "NetworkInterfaceName": {
                "type": "string",
                "description": "Name of your ENI. It is a string of [2, 128]  Chinese or English characters. It must begin with a letter and can contain numbers, underscores (_), colons (:), or hyphens (-)."
              },
              "PrimaryIpAddress": {
                "type": "string",
                "description": "The primary private IP address of the ENI."
              },
              "SecurityGroupId": {
                "type": "string",
                "description": "The ID of the security group that the ENI joins. The security group and the ENI must be in a same VPC."
              },
              "VSwitchId": {
                "type": "string",
                "description": "VSwitch ID of the specified VPC."
              }
            }
          },
          "maxItems": 8
        },
        "NetworkType": {
          "type": "string",
          "description": "Instance network type. Support 'vpc' and 'classic'",
          "Enum": [
            "vpc",
            "classic"
          ]
        },
        "RamRoleName": {
          "type": "string",
          "description": "Instance RAM role name. The name is provided and maintained by Resource Access Management (RAM) and can be queried using ListRoles. For more information, see RAM API CreateRole and ListRoles."
        },
        "SecurityEnhancementStrategy": {
          "type": "string",
          "description": "Activate or deactivate security enhancement,Value range: \"Active\" and \"Deactive\"",
          "Enum": [
            "Active",
            "Deactive"
          ]
        },
        "SecurityGroupId": {
          "type": "string",
          "description": "Security group to create ecs instance. For classic instance need the security group not belong to VPC, for VPC instance, please make sure the security group belong to specified VPC."
        },
        "SpotPriceLimit": {
          "type": "string",
          "description": "The hourly price threshold of a instance, and it takes effect only when parameter InstanceChargeType is PostPaid. Three decimals is allowed at most. "
        },
        "SpotStrategy": {
          "type": "string",
          "description": "The spot strategy of a Pay-As-You-Go instance, and it takes effect only when parameter InstanceChargeType is PostPaid. Value range: \"NoSpot: A regular Pay-As-You-Go instance\", \"SpotWithPriceLimit: A price threshold for a spot instance, \"\"SpotAsPriceGo: A price that is based on the highest Pay-As-You-Go instance. \"",
          "Enum": [
            "NoSpot",
            "SpotWithPriceLimit",
            "SpotAsPriceGo"
          ]
        },
        "SystemDiskCategory": {
          "type": "string",
          "description": "Category of system disk. support cloud|cloud_efficiency|cloud_ssd|cloud_essd|ephemeral_ssd",
          "Enum": [
            "cloud",
            "cloud_efficiency",
            "cloud_ssd",
            "cloud_essd",
            "ephemeral_ssd"
          ]
        },
        "SystemDiskDescription": {
          "type": "string",
          "description": "Description of created system disk."
        },
        "SystemDiskDiskName": {
          "type": "string",
          "description": "Name of created system disk."
        },
        "SystemDiskSize": {
          "type": "number",
          "description": "Disk size of the system disk, range from 20 to 500 GB. If you specify with your own image, make sure the system disk size bigger than image size. ",
          "minimum": 20
        },
        "Tags": {
          "type": "array",
          "description": "Tags to attach to instance, security group, disk and network interface.",
          "items": {
            "type": "object",
            "properties": {
              "Key": {
                "type": "string"
              },
              "Value": {
                "type": "string"
              }
            }
          },
          "maxItems": 20
        },
        "TemplateTags": {
          "type": "array",
          "description": "Template tags to attach to launch template.",
          "items": {
            "type": "object",
            "properties": {
              "Key": {
                "type": "string"
              },
              "Value": {
                "type": "string"
              }
            }
          },
          "maxItems": 20
        },
        "UserData": {
          "type": "string",
          "description": "User data to pass to instance. [1, 16KB] characters."
        },
        "VSwitchId": {
          "type": "string",
          "description": "The vSwitch Id to create ecs instance."
        },
        "VersionDescription": {
          "type": "string",
          "description": "Description for version 1 of launch template."
        },
        "ZoneId": {
          "type": "string",
          "description": "Current zone to create the instance."
        }
      }
    }
