apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ecs-networkinterfacepermission
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ECS_NetworkInterfacePermission
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "NetworkInterfaceId",
        "Permission",
        "AccountId"
      ],
      "properties": {
        "AccountId": {
          "type": "string",
          "description": "the account id"
        },
        "NetworkInterfaceId": {
          "type": "string",
          "description": "Network interface id"
        },
        "Permission": {
          "type": "string",
          "description": "the permission",
          "default": "InstanceAttach"
        }
      }
    }
