apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: kms-key
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: KMS_Key
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "Description": {
          "type": "string",
          "description": "The description of the CMK. Length constraints: Minimum length of 0 characters. Maximum length of 8192 characters.",
          "maxLength": 8192
        },
        "Enable": {
          "type": "boolean",
          "description": "Specifies whether the key is enabled. Defaults to true.",
          "default": true
        },
        "KeyUsage": {
          "type": "string",
          "description": "The intended use of the CMK. Default value: ENCRYPT/DECRYPT.",
          "default": "ENCRYPT/DECRYPT"
        },
        "PendingWindowInDays": {
          "type": "integer",
          "description": "The waiting period, specified in number of days. During this period, you can cancel the CMK in PendingDeletion status. After the waiting period expires, you cannot cancel the deletion. The value must be between 7 and 30. Default value is 30.",
          "default": 30,
          "minimum": 7,
          "maximum": 30
        }
      }
    }
