apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: mns-queue
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: MNS_Queue
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "QueueName"
      ],
      "properties": {
        "DelaySeconds": {
          "type": "integer",
          "description": "It is measured in seconds. All messages sent to the queue can be consumed until the DelaySeconds expires.\nAn integer between 0 and 604800 (7 days). The default value is 0",
          "default": 0,
          "maximum": 604800
        },
        "LoggingEnabled": {
          "type": "boolean",
          "description": "Whether to enable log management. \"true\" indicates that log management is enabled, whereas \"false\" indicates that log management is disabled. \nThe default value is false",
          "default": false
        },
        "MaximumMessageSize": {
          "type": "integer",
          "description": "Maximum body length of a message sent to the queue, measured in bytes.\nAn integer between 1024 (1K) and 65536 (64K). The default value is 65536 (64K).",
          "default": 65536,
          "minimum": 1024,
          "maximum": 65536
        },
        "MessageRetentionPeriod": {
          "type": "integer",
          "description": "Maximum lifetime of the message in the queue, measured in seconds. After the time specified by this parameter expires, the message will be deleted no matter whether it has been consumed or not.\nAn integer between 60 (1 minute) and 1296000 (15 days). The default value is 345600 (4 days)",
          "default": 345600,
          "minimum": 60,
          "maximum": 604800
        },
        "PollingWaitSeconds": {
          "type": "integer",
          "description": "It is the maximum time that a ReceiveMessage request could be waiting for any incoming messages, while there are no message in the queue. Measured in seconds.\nAn integer between 0 and 30 seconds. The default value is 0 (seconds)",
          "default": 0,
          "maximum": 30
        },
        "QueueName": {
          "type": "string",
          "description": "Queue name",
          "minLength": 1,
          "maxLength": 256
        },
        "VisibilityTimeout": {
          "type": "integer",
          "description": "Duration in which a message stays in Inactive status after it is consumed from the queue. Measured in seconds.\nAn integer between 1 and 43200 (12 hours). The default value is 30 (seconds)",
          "default": 30,
          "minimum": 1,
          "maximum": 43200
        }
      }
    }
