apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: mongodb-instance
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: MONGODB_Instance
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "DBInstanceClass",
        "DBInstanceStorage"
      ],
      "properties": {
        "AccountPassword": {
          "type": "string",
          "description": "Root account password, can contain the letters, numbers or underscores the composition, length of 6~32 bit."
        },
        "AutoRenew": {
          "type": "boolean",
          "description": "Indicates whether automatic renewal is enabled for the instance. Valid values:true: Automatic renewal is enabled.false: Automatic renewal is not enabled. You must renew the instance manually.Default value: false."
        },
        "BackupId": {
          "type": "string",
          "description": "Specific backup set Id."
        },
        "BusinessInfo": {
          "type": "string",
          "description": "The business information. It is an additional parameter."
        },
        "ChargeType": {
          "type": "string",
          "description": "The billing method of the instance.values:PostPaid: Pay-As-You-Go.PrePaid: Subscription.Default value: PostPaid",
          "default": "PostPaid",
          "Enum": [
            "PostPaid",
            "PrePaid"
          ]
        },
        "CouponNo": {
          "type": "string",
          "description": "The coupon code. Default value:youhuiquan_promotion_option_id_for_blank."
        },
        "DBInstanceClass": {
          "type": "string",
          "description": "MongoDB instance supported instance type, make sure it should be correct."
        },
        "DBInstanceDescription": {
          "type": "string",
          "description": "Description of created database instance."
        },
        "DBInstanceStorage": {
          "type": "integer",
          "description": "Database instance storage size. MongoDB is [5,1000], increased every 5 GB, Unit in GB"
        },
        "DatabaseNames": {
          "type": "string",
          "description": "The name of the database."
        },
        "EngineVersion": {
          "type": "string",
          "description": "Database instance version.Support 3.2, 3.4, 4.0",
          "default": "3.4",
          "Enum": [
            "3.2",
            "3.4",
            "4.0",
            "4.2"
          ]
        },
        "NetworkType": {
          "type": "string",
          "description": "The instance network type. Support 'CLASSIC' and 'VPC' only, default is 'CLASSIC'.",
          "Enum": [
            "CLASSIC",
            "VPC"
          ]
        },
        "Period": {
          "type": "integer",
          "description": "The subscription period of the instance.Unit: months.Valid values: [1~9], 12, 24, 36. Default to 1.",
          "default": 1,
          "Enum": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            12,
            24,
            36
          ]
        },
        "ReadonlyReplicas": {
          "type": "integer",
          "description": "Number of read-only nodes, in the range of 1-5.",
          "Enum": [
            1,
            2,
            3,
            4,
            5
          ]
        },
        "ReplicationFactor": {
          "type": "integer",
          "description": "The number of nodes in the replica set. Allowed values: [3, 5, 7], default to 3.",
          "Enum": [
            3,
            5,
            7
          ]
        },
        "ResourceGroupId": {
          "type": "string",
          "description": "The ID of the resource group."
        },
        "RestoreTime": {
          "type": "string",
          "description": "The time to restore the cloned instance to. The format is yyyy-MM-ddTHH:mm:ssZ.This parameter can only be specified when this operation is called to clone instances.You must also specify theSrcDBInstanceIdparameter and theBackupIdparameter.You can clone instances to any restore time in the past seven days."
        },
        "SecurityIPArray": {
          "type": "string",
          "description": "Security ips to add or remove."
        },
        "SrcDBInstanceId": {
          "type": "string",
          "description": "Create an instance of the backup set based on an instance."
        },
        "StorageEngine": {
          "type": "string",
          "description": "Database storage engine.Support WiredTiger, RocksDB",
          "default": "WiredTiger",
          "Enum": [
            "WiredTiger",
            "RocksDB"
          ]
        },
        "VSwitchId": {
          "type": "string",
          "description": "The vSwitch Id to create mongodb instance."
        },
        "VpcId": {
          "type": "string",
          "description": "The VPC id to create mongodb instance."
        },
        "ZoneId": {
          "type": "string",
          "description": "current zone to create the instance."
        }
      }
    }
