apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: oos-template
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: OOS_Template
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "TemplateName",
        "Content"
      ],
      "properties": {
        "Content": {
          "type": "string",
          "description": "The content of the template. The template must be in the JSON or YAML format. Maximum size: 64 KB.",
          "maxLength": 65536
        },
        "Tags": {
          "maxProperties": 20
        },
        "TemplateName": {
          "type": "string",
          "description": "The name of the template. The template name can be up to 200 characters in length. The name can contain letters, digits, hyphens (-), and underscores (_). It cannot start with ALIYUN, ACS, ALIBABA, or ALICLOUD.",
          "maxLength": 200
        }
      }
    }
