apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ots-table
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: OTS_Table
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "PrimaryKey",
        "InstanceName",
        "TableName"
      ],
      "properties": {
        "Columns": {
          "type": "array",
          "description": "Attribute column for table store.",
          "items": {
            "type": "object",
            "required": [
              "Name",
              "Type"
            ],
            "properties": {
              "Name": {
                "type": "string",
                "description": "The column name of the column.",
                "pattern": "[_a-zA-Z][_a-zA-Z0-9]{0,254}"
              },
              "Type": {
                "type": "string",
                "description": "The type of the column.",
                "Enum": [
                  "INTEGER",
                  "STRING",
                  "BINARY",
                  "BOOLEAN",
                  "DOUBLE"
                ]
              }
            }
          }
        },
        "DeviationCellVersionInSec": {
          "type": "integer",
          "description": "Maximum version deviation. The purpose is mainly to prohibit writing and expected large data, such as setting the deviation_cell_version_in_sec to 1000, and if the current timestamp is 10000, the timestamp range allowed to be written is [10000 - 1000, 10000 + 1000]. The valid value is 1-9223372036854775807. Defaults to 86400.",
          "default": 86400,
          "minimum": 1,
          "maximum": 9223372036854776000
        },
        "InstanceName": {
          "type": "string",
          "description": "The name of the OTS instance in which table will locate.",
          "pattern": "[a-zA-Z][-a-zA-Z0-9]{1,14}[a-zA-Z0-9]"
        },
        "MaxVersions": {
          "type": "integer",
          "description": "The maximum number of versions stored in this table. The valid value is 1-2147483647. Default to 1.",
          "default": 1,
          "minimum": 1,
          "maximum": 2147483647
        },
        "PrimaryKey": {
          "type": "array",
          "description": "It describes the attribute value of primary key. The number of primary_key should not be less than one and not be more than four.",
          "items": {
            "type": "object",
            "required": [
              "Name",
              "Type"
            ],
            "properties": {
              "Name": {
                "type": "string",
                "description": "Name for primary key.",
                "pattern": "[_a-zA-Z][_a-zA-Z0-9]{0,254}"
              },
              "Type": {
                "type": "string",
                "description": "Type for primary key. Only INTEGER, STRING or BINARY is allowed.",
                "Enum": [
                  "INTEGER",
                  "STRING",
                  "BINARY"
                ]
              }
            }
          },
          "minItems": 1,
          "maxItems": 4
        },
        "ReservedThroughput": {
          "type": "object",
          "required": [
            "Write",
            "Read"
          ],
          "properties": {
            "Read": {
              "type": "integer",
              "description": "The read service capability unit consumed by this operation or the reserved read throughput of the table. Default to 0.",
              "default": 0,
              "maximum": 5000
            },
            "Write": {
              "type": "integer",
              "description": "The write service capability unit consumed by this operation or the reserved write throughput of the table. Default to 0.",
              "default": 0,
              "maximum": 5000
            }
          }
        },
        "SecondaryIndices": {
          "type": "array",
          "description": "The secondary indices of the table.",
          "items": {
            "type": "object",
            "required": [
              "IndexName",
              "Columns",
              "PrimaryKeys"
            ],
            "properties": {
              "Columns": {
                "type": "array",
                "description": "The columns of the index.",
                "items": {}
              },
              "IndexName": {
                "type": "string",
                "description": "The index name."
              },
              "IndexType": {
                "type": "string",
                "description": "The index type",
                "default": "Global",
                "Enum": [
                  "Global",
                  "Local"
                ]
              },
              "PrimaryKeys": {
                "type": "array",
                "description": "The primary keys of the index.",
                "items": {}
              }
            }
          }
        },
        "TableName": {
          "type": "string",
          "description": "The table name of the OTS instance.",
          "pattern": "[_a-zA-Z][_a-zA-Z0-9]{0,254}"
        },
        "TimeToLive": {
          "type": "integer",
          "description": "The retention time of data stored in this table (unit: second). The value maximum is 2147483647 and -1 means never expired. Default to -1.",
          "default": -1,
          "minimum": -1,
          "maximum": 2147483647
        }
      }
    }
