apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: polardb-account
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: POLARDB_Account
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "AccountPassword",
        "AccountName",
        "DBClusterId"
      ],
      "properties": {
        "AccountDescription": {
          "type": "string",
          "description": "The description of the database account. The description must comply with the following rules:\n- It cannot start with http:// or https://.\n- It must be 2 to 256 characters in length.",
          "minLength": 2,
          "maxLength": 256
        },
        "AccountName": {
          "type": "string",
          "description": "The name of the database account. The name must comply with the following rules:\n- It must start with a lowercase letter and consist of lowercase letters, digits, and underscores (_).\n- It can be up to 16 characters in length.",
          "minLength": 1,
          "maxLength": 16
        },
        "AccountPassword": {
          "type": "string",
          "description": "The password of the database account. The password must comply with the following rules:\n- It must consist of uppercase letters, lowercase letters, digits, and special characters.\n- Special characters include exclamation points (!), number signs (#), dollar signs ($), percent signs (%), carets (^), ampersands (\u0026), asterisks (*), parentheses (()), underscores (_), plus signs (+), hyphens (-), and equal signs (=).\n- It must be 8 to 32 characters in length.",
          "minLength": 8,
          "maxLength": 32
        },
        "AccountPrivilege": {
          "type": "string",
          "description": "The permissions of the database account on the database. Valid values:\nReadWrite: has read and write permissions on the database.\nReadOnly: has the read-only permission on the database.\nDMLOnly: runs only data manipulation language (DML) statements.\nDDLOnly: runs only data definition language (DDL) statements.\nDefault value: ReadWrite.\nSeparate multiple permissions with a comma (,)."
        },
        "AccountType": {
          "type": "string",
          "description": "The type of the database account. Valid values:\n- Normal: standard account\n- Super: privileged account\nDefault value: Super.\nCurrently, POLARDB for PostgreSQL and POLARDB compatible with Oracle do not support standard accounts.\nYou can create only one privileged account for an ApsaraDB for POLARDB cluster.",
          "Enum": [
            "Normal",
            "Super"
          ]
        },
        "DBClusterId": {
          "type": "string",
          "description": "The ID of the ApsaraDB for POLARDB cluster for which a database account is to be created."
        },
        "DBName": {
          "type": "string",
          "description": "The name of the database whose access permissions are to be granted to the database account. Separate multiple databases with a comma (,)."
        }
      }
    }
