apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: pvtz-zonevpcbinder
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: PVTZ_ZoneVpcBinder
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Vpcs",
        "ZoneId"
      ],
      "properties": {
        "Vpcs": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "RegionId",
              "VpcId"
            ],
            "properties": {
              "RegionId": {
                "type": "string",
                "description": "Vpcs attribute, region Id"
              },
              "VpcId": {
                "type": "string",
                "description": "Vpcs attribute, vpc Id"
              }
            }
          },
          "maxItems": 10
        },
        "ZoneId": {
          "type": "string",
          "description": "Zone Id"
        }
      }
    }
