apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ram-user
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: RAM_User
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "UserName"
      ],
      "properties": {
        "DisplayName": {
          "type": "string",
          "description": "Display name, up to 12 characters or Chinese characters."
        },
        "Groups": {
          "type": "array",
          "description": "A name of a group to which you want to add the user.",
          "items": {}
        },
        "LoginProfile": {
          "type": "object",
          "properties": {
            "MFABindRequired": {
              "type": "boolean",
              "description": "Specifies whether the user must bind a multi factor authentication device at the next logon.",
              "default": false
            },
            "Password": {
              "type": "string",
              "description": "The password for the user.",
              "minLength": 8,
              "maxLength": 32
            },
            "PasswordResetRequired": {
              "type": "boolean",
              "description": "Specifies whether the user is required to set a new password the next time the user logs in to the AliCloud Management Console.",
              "default": false
            }
          }
        },
        "MobilePhone": {
          "type": "string",
          "description": "Phone number of ram user."
        },
        "Policies": {
          "type": "array",
          "description": "Describes what actions are allowed on what resources.",
          "items": {
            "type": "object",
            "required": [
              "PolicyName",
              "PolicyDocument"
            ],
            "properties": {
              "Description": {
                "type": "string",
                "description": "Specifies the authorization policy description, containing up to 1024 characters.",
                "maxLength": 1024
              },
              "PolicyDocument": {
                "type": "object",
                "properties": {
                  "Statement": {
                    "type": "array",
                    "description": "A policy consists of one or more statements.",
                    "items": {
                      "type": "object",
                      "properties": {
                        "Action": {
                          "type": "array",
                          "description": "What actions you will allow.",
                          "items": {}
                        },
                        "Condition": {},
                        "Effect": {
                          "type": "string",
                          "description": "What the effect will be when the user requests access-either allow or deny."
                        },
                        "Resource": {
                          "type": "array",
                          "description": "Which resources you allow the action on.",
                          "items": {}
                        }
                      }
                    }
                  },
                  "Version": {
                    "type": "string",
                    "description": "You can use versions to track changes to a managed policy."
                  }
                }
              },
              "PolicyName": {
                "type": "string",
                "description": "Specifies the authorization policy name, containing up to 128 characters."
              }
            }
          }
        },
        "UserName": {
          "type": "string",
          "description": "Specifies the user name, containing up to 64 characters."
        }
      }
    }
