apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: rds-account
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: RDS_Account
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "DBInstanceId",
        "AccountPassword",
        "AccountName"
      ],
      "properties": {
        "AccountDescription": {
          "type": "string",
          "description": "Account remarks.\nIt cannot begin with http:// or https://.\nIt must start with a Chinese character or English letter.\nIt can include Chinese and English characters/letters, underscores (_), hyphens (-), and digits.\nThe length may be 2-256 characters."
        },
        "AccountName": {
          "type": "string",
          "description": "Account name, which must be unique and meet the following requirements:\nStart with a letter;\nConsist of lower-case letters, digits, and underscores (_);\nContain no more than 16 characters.\nFor other invalid characters, see Forbidden keywords table."
        },
        "AccountPassword": {
          "type": "string",
          "description": "The account password for the database instance. It may consist of letters, digits, or underlines, with a length of 8 to 32 characters.",
          "minLength": 8,
          "maxLength": 32
        },
        "AccountType": {
          "type": "string",
          "description": "Privilege type of account.\nNormal: Common privilege.\nSuper: High privilege. And the default value is Normal.\nThis parameter is valid for MySQL 5.5/5.6 only.\nMySQL 5.7, SQL Server 2012/2016, PostgreSQL, and PPAS each can have only one initial account. Other accounts are created by the initial account that has logged on to the database.",
          "default": "Normal",
          "Enum": [
            "Normal",
            "Super"
          ]
        },
        "DBInstanceId": {
          "type": "string",
          "description": "RDS instance ID."
        }
      }
    }
