apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: redis-instance
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: REDIS_Instance
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "Capacity": {
          "type": "integer",
          "description": "The storage capacity of redis instance.range from 1 to 512, in GB.",
          "Enum": [
            1,
            2,
            4,
            8,
            16,
            32,
            64,
            128,
            256,
            512
          ]
        },
        "EngineVersion": {
          "type": "string",
          "description": "Engine version. Supported values: 2.8, 4.0 and 5.0. Default value: 2.8.",
          "default": "2.8",
          "Enum": [
            "2.8",
            "4.0",
            "5.0"
          ]
        },
        "EvictionPolicy": {
          "type": "string",
          "description": "The eviction policy of cache data storage.",
          "Enum": [
            "noeviction",
            "allkeys-lru",
            "volatile-lru",
            "allkeys-random",
            "volatile-random",
            "volatile-ttl"
          ]
        },
        "InstanceClass": {
          "type": "string",
          "description": "Redis instance type. Refer the Redis instance type reference, such as 'redis.master.small.default', 'redis.master.4xlarge.default', 'redis.sharding.mid.default' etc"
        },
        "InstanceName": {
          "type": "string",
          "description": "Display name of the instance, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "Password": {
          "type": "string",
          "description": "The password of redis instance.length 8 to 30 characters, need to contain both uppercase and lowercase letters and numbers"
        },
        "VSwitchId": {
          "type": "string",
          "description": "The vSwitch Id to create ecs instance."
        },
        "VpcId": {
          "type": "string",
          "description": "The VPC id to create ecs instance."
        },
        "ZoneId": {
          "type": "string",
          "description": "The zone id of input region."
        }
      }
    }
