apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: ros-stack
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: ROS_Stack
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "TemplateURL"
      ],
      "properties": {
        "Parameters": {},
        "TemplateURL": {
          "type": "string",
          "description": "The URL of a template that specifies the stack to be created as a resource. Supported url schemas: https, https and oss. For example:\nhttp://www.my-site.com/simple-tpl\nhttps://www.my-site.com/simple-tpl\noss://stacks/simple-tpl\noss://stacks/simple-tpl?RegionId=cn-hangzhou",
          "maxLength": 1024
        },
        "TimeoutMins": {
          "type": "number",
          "description": "The length of time, in minutes, to wait for the nested stack creation or update. Default to 60 minutes.",
          "default": 60
        }
      }
    }
