apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: sag-acl
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: SAG_ACL
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string",
          "description": "Access control name.\nThe length is 2-128 characters. It must start with a letter or Chinese. It can contain numbers, periods (.), underscores (_) and dashes (-), but cannot start with http:// or https://."
        }
      }
    }
