apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: slb-backendserverattachment
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: SLB_BackendServerAttachment
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "LoadBalancerId"
      ],
      "properties": {
        "BackendServerList": {
          "type": "array",
          "description": "The comma delimited instance id list.If the property \"BackendServers\" is setting, this property will be ignored.",
          "items": {}
        },
        "BackendServerWeightList": {
          "type": "array",
          "description": "The comma delimited weight list. If no value specified will use 100. If the length is small than \"BackendServerList\", it will copy the last one to fill the array.If the property \"BackendServers\" is setting, this property will be ignored.",
          "items": {}
        },
        "BackendServers": {
          "type": "array",
          "description": "The list of ECS instance, which will attached to load balancer.",
          "items": {
            "type": "object",
            "required": [
              "ServerId",
              "Weight"
            ],
            "properties": {
              "ServerId": {
                "type": "string",
                "description": "Need one valid ECS instance id. The instance status should running."
              },
              "Weight": {
                "type": "integer",
                "description": "The weight of backend server of load balancer. From 0 to 100, 0 means offline. Default is 100.",
                "maximum": 100
              }
            }
          }
        },
        "LoadBalancerId": {
          "type": "string",
          "description": "The id of load balancer."
        }
      }
    }
