apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: slb-rule
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: SLB_Rule
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "RuleList",
        "LoadBalancerId",
        "ListenerPort"
      ],
      "properties": {
        "ListenerPort": {
          "type": "integer",
          "description": "The front-end HTTPS listener port of the Server Load Balancer instance. Valid value:\n1-65535",
          "minimum": 1,
          "maximum": 65535
        },
        "LoadBalancerId": {
          "type": "string",
          "description": "The ID of Server Load Balancer instance."
        },
        "RuleList": {
          "type": "array",
          "description": "The forwarding rules to add.",
          "items": {
            "type": "object",
            "required": [
              "VServerGroupId",
              "RuleName"
            ],
            "properties": {
              "Domain": {
                "type": "string",
                "description": "The domain name."
              },
              "RuleName": {
                "type": "string",
                "description": "The name of the forwarding rule."
              },
              "Url": {
                "type": "string",
                "description": "The URL."
              },
              "VServerGroupId": {
                "type": "string",
                "description": "The ID of the VServer group associated with the forwarding rule."
              }
            }
          },
          "minItems": 1,
          "maxItems": 10
        }
      }
    }
