apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: sls-index
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: SLS_Index
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "FullTextIndex",
        "LogstoreName",
        "ProjectName"
      ],
      "properties": {
        "FullTextIndex": {
          "type": "object",
          "required": [
            "Enable"
          ],
          "properties": {
            "CaseSensitive": {
              "type": "boolean",
              "description": "Whether it is case sensitive. Default to false.",
              "default": false
            },
            "Delimiter": {
              "type": "string",
              "description": "Delimiter. Default to (( , '\";=()[]{}?@\u0026\u003c\u003e/:\\n\\t\\r )).",
              "default": ", '\";=()[]{}?@\u0026\u003c\u003e/:\\n\\t\\r"
            },
            "Enable": {
              "type": "boolean",
              "description": "Whether to enable full-text indexing. Default to true.",
              "default": true
            },
            "IncludeChinese": {
              "type": "boolean",
              "description": "Whether it contains Chinese. Default to false.",
              "default": false
            }
          }
        },
        "KeyIndices": {
          "type": "array",
          "description": "Key index configurations.\nFull-text indexing and key indexing must have at least one enabled.",
          "items": {
            "type": "object",
            "required": [
              "Type",
              "Name"
            ],
            "properties": {
              "Alias": {
                "type": "string",
                "description": "Key alias."
              },
              "CaseSensitive": {
                "type": "boolean",
                "description": "Whether it is case sensitive. It takes effect when Type is text or json. Default to false.",
                "default": false
              },
              "Delimiter": {
                "type": "string",
                "description": "Delimiter. It takes effect when Type is text or json. Default to (( , '\";=()[]{}?@\u0026\u003c\u003e/:\\n\\t\\r )).",
                "default": ", '\";=()[]{}?@\u0026\u003c\u003e/:\\n\\t\\r"
              },
              "EnableAnalytics": {
                "type": "boolean",
                "description": "Whether this key is enabled for statistics. Default to false for json type, else true."
              },
              "IncludeChinese": {
                "type": "boolean",
                "description": "Whether it contains Chinese. It takes effect when Type is text or json. Default to false.",
                "default": false
              },
              "JsonKeyIndices": {
                "type": "array",
                "description": "Json key index configurations.",
                "items": {
                  "type": "object",
                  "required": [
                    "Name",
                    "Type"
                  ],
                  "properties": {
                    "Alias": {
                      "type": "string",
                      "description": "Json key alias."
                    },
                    "EnableAnalytics": {
                      "type": "boolean",
                      "description": "Whether this json key is enabled for statistics. Default to true.",
                      "default": true
                    },
                    "Name": {
                      "type": "string",
                      "description": "Json key name. It can be nested by dot(.), such as k1.k2.k3."
                    },
                    "Type": {
                      "type": "string",
                      "description": "Json key type. Allowed types: text, long, double. Default to text.",
                      "default": "text",
                      "Enum": [
                        "text",
                        "long",
                        "double"
                      ]
                    }
                  }
                }
              },
              "Name": {
                "type": "string",
                "description": "Key name."
              },
              "Type": {
                "type": "string",
                "description": "Key type. Allowed types: text, long, double, json. Default to text.",
                "default": "text",
                "Enum": [
                  "text",
                  "long",
                  "double",
                  "json"
                ]
              }
            }
          }
        },
        "LogReduce": {
          "type": "boolean",
          "description": "Whether to enable log reduce. Default to false.",
          "default": false
        },
        "LogstoreName": {
          "type": "string",
          "description": "Logstore name:\n1. Only supports lowercase letters, numbers, hyphens (-) and underscores (_).\n2. Must start and end with lowercase letters and numbers.\n3. The name length is 3-63 characters.",
          "minLength": 3,
          "maxLength": 63
        },
        "ProjectName": {
          "type": "string",
          "description": "Project name:\n1. Only supports lowercase letters, numbers, hyphens (-) and underscores (_).\n2. Must start and end with lowercase letters and numbers.\n3. The name length is 3-63 characters.",
          "minLength": 3,
          "maxLength": 63,
          "pattern": "^[a-zA-Z0-9_-]+$"
        }
      }
    }
