apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: sls-machinegroup
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: SLS_MachineGroup
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "GroupAttribute": {
          "type": "string",
          "description": "Group attribute, default is null. The object value is groupToic and externalName"
        },
        "GroupName": {
          "type": "string",
          "description": "Display name of the group name, the Project only. [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "GroupType": {
          "type": "string",
          "description": "MachineGroup type, the value is empty or Armory",
          "Enum": [
            "",
            "Armory"
          ]
        },
        "MachineIdentifyType": {
          "type": "string",
          "description": "Machine indentify type, the value is 'ip' or 'userdefined' ",
          "Enum": [
            "ip",
            "userdefined"
          ]
        },
        "MachineList": {
          "type": "array",
          "description": "The machine tag, the value is ip or userdefined-id.",
          "items": {}
        },
        "ProjectName": {
          "type": "string",
          "description": "MachineGroup created in project."
        }
      }
    }
