apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: vpc-routetableassociation
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: VPC_RouteTableAssociation
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "RouteTableId",
        "VSwitchId"
      ],
      "properties": {
        "RouteTableId": {
          "type": "string",
          "description": "The ID of the route table."
        },
        "VSwitchId": {
          "type": "string",
          "description": "The ID of the VSwitch."
        }
      }
    }
