apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: vpc-snatentry
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: VPC_SnatEntry
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "SnatTableId",
        "SnatIp"
      ],
      "properties": {
        "SnatEntryName": {
          "type": "string",
          "description": "he name of the SNAT rule is 2-128 characters long and must start with a letter or Chinese, but cannot begin with HTTP:// or https://."
        },
        "SnatIp": {
          "type": "string",
          "description": "The public IP address. Separate multiple EIPs with commas."
        },
        "SnatTableId": {
          "type": "string",
          "description": "The ID of the SNAT table."
        },
        "SourceVSwitchIds": {
          "type": "array",
          "description": "The ID of the VSwitch to access the Internet.",
          "items": {}
        }
      }
    }
