apiVersion: core.oam.dev/v1alpha1
kind: WorkloadType
metadata:
  name: vpc-routerinterface
spec:
  group: ros.aliyun.com
  version: v1alpha1
  names:
    kind: VPC_RouterInterface
  workloadSettings: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "RouterId",
        "Role"
      ],
      "properties": {
        "AccessPointId": {
          "type": "string",
          "description": "Access point ID. If 'RouterType' is specified as 'VBR', the value is required."
        },
        "AutoPay": {
          "type": "boolean",
          "description": "Indicates whether automatic payment is enabled. Valid values:false: Automatic payment is disabled. You need to go to Orders to make the payment once an order is generated. true: Automatic payment is enabled. The payment is automatically made."
        },
        "Description": {
          "type": "string",
          "description": "Custom description of the RouterInterface, [2, 256] characters. Don't fill or empty, the default is empty."
        },
        "HealthCheckSourceIp": {
          "type": "string",
          "description": "Source IP address of the packet for leased line HealthCheck in leased line disaster tolerance and ECMP scenarios. It is valid only for a VRouter RouterInterface with a peer on a VBR. The source IP address must be in the VPC of the local VRouter and is not used. HealthCheckSourceIp and HealthCheckTargetIp parameters must be both specified or left unspecified."
        },
        "HealthCheckTargetIp": {
          "type": "string",
          "description": "Target IP address of the packet for leased line HealthCheck in leased line disaster tolerance and ECMP scenarios. It is valid only for a VRouter RouterInterface with a peer on a VBR. Usually you can use the CPE IP address of the leased line user's client (that is, the PeerGatewayIP on the VBR of the peer RouterInterface), you can also specify another IP address of the leased line user's client as the HealthCheck target IP address. HealthCheckSourceIp and HealthCheckTargetIp parameters must be both specified or left unspecified."
        },
        "InstanceChargeType": {
          "type": "string",
          "description": "The billing method of the router interface. Valid values: PrePaid (Subscription), PostPaid (default, Pay-As-You-Go)",
          "default": "PostPaid",
          "Enum": [
            "PrePaid",
            "PostPaid"
          ]
        },
        "Name": {
          "type": "string",
          "description": "Custom name of the RouterInterface, [2, 128] English or Chinese characters, must start with a letter or Chinese in size, can contain numbers, '_' or '.', '-'"
        },
        "OppositeAccessPointId": {
          "type": "string",
          "description": "Access point ID of the connection peer RouterInterface. If 'OppositeRouterType' is specified as 'VBR', the value is required."
        },
        "OppositeInterfaceOwnerId": {
          "type": "string",
          "description": "Owner account ID of the connection peer RouterInterface. The default value is current user Id."
        },
        "OppositeRegionId": {
          "type": "string",
          "description": "The region where the connection peer RouterInterface locates. The default value is region where stack is created."
        },
        "OppositeRouterId": {
          "type": "string",
          "description": "The router ID of the connection peer RouterInterface."
        },
        "OppositeRouterType": {
          "type": "string",
          "description": "Router type of the connection peer router. Now support 'VRouter|VBR'. If 'RouterType' is specified as 'VBR', the value must be 'VRouter'.",
          "default": "VRouter",
          "Enum": [
            "VRouter",
            "VBR"
          ]
        },
        "Period": {
          "type": "number",
          "description": "Prepaid time period. It could be from 1 to 9 when PricingCycle is Month, or 1 to 3 when PricingCycle is Year. Default value is 3.",
          "Enum": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
          ]
        },
        "PricingCycle": {
          "type": "string",
          "description": "Unit of the payment cycle. It could be Month (default) or Year.",
          "Enum": [
            "Month",
            "Year"
          ]
        },
        "Role": {
          "type": "string",
          "description": "RouterInterface role. Now support 'InitiatingSide|AcceptingSide'. If 'RouterType' is specified as 'VBR', the value must be 'InitiatingSide'.If 'OppositeRouterType' is specified as 'VBR', the value must be 'AcceptingSide'.",
          "Enum": [
            "InitiatingSide",
            "AcceptingSide"
          ]
        },
        "RouterId": {
          "type": "string",
          "description": "The router ID to create RouterInterface."
        },
        "RouterType": {
          "type": "string",
          "description": "Router type. Now support 'VRouter|VBR'",
          "default": "VRouter",
          "Enum": [
            "VRouter",
            "VBR"
          ]
        },
        "Spec": {
          "type": "string",
          "description": "RouterInterface specification. If 'Role' is specified as 'InitiatingSide', the value is required. If 'Role' is specified as 'AcceptingSide', the value is set as 'Negative' by default."
        }
      }
    }
